# Generated by Django 4.2.15 on 2024-08-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('OAM_address', models.CharField(max_length=200)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
